import {
  faSun,
  faMoon,
  faWhistle,
  faMagnifyingGlass,
  faArrowLeft,
  faArrowRight,
  faMaximize,
  faBars,
  faLockOpen,
  faUser,
  faUserPlus,
  faGear,
  faRightFromBracket,
  faHome,
  faCloud,
  faMagnifyingGlassDollar,
  faCircleInfo,
  faCreditCard,
  faDollarSign,
  faSackDollar,
  faHouseChimney,
  faPhone,
  faShieldCheck,
} from "@fortawesome/pro-light-svg-icons";

import {
  faFacebookF,
  faGoogle,
  faTwitter,
} from "@fortawesome/free-brands-svg-icons";

const Icons = {
  faSun,
  faMoon,
  faWhistle,
  faMagnifyingGlass,
  faArrowLeft,
  faArrowRight,
  faMaximize,
  faBars,
  faLockOpen,
  faUser,
  faUserPlus,
  faGear,
  faRightFromBracket,
  faHome,
  faCloud,
  faCircleInfo,
  faFacebookF,
  faGoogle,
  faTwitter,
  faCreditCard,
  faMagnifyingGlassDollar,
  faDollarSign,
  faSackDollar,
  faHouseChimney,
  faPhone,
  faShieldCheck,
};

export default Icons;
